name: news_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # To manage responsiveness of UI:
  flutter_screenutil: ^5.6.1

  # To manage navigation, state management etc.
  get: ^4.6.5

  # To get device id:
  platform_device_id: ^1.0.1

  # To implement otp text-field(UI):
  pinput: ^2.2.31

  # To handle API requests:
  http: ^0.13.5

  # To store data locally:
  get_storage: ^2.1.1

  # To handle loader while API is being called(UI):
  flutter_progress_hud: ^2.0.2

  # To get app info:
  package_info_plus: ^3.0.3

  # To manage cache in the app:
  flutter_cache_manager: ^3.3.0

  # To manage cache of the network image:
  cached_network_image: ^3.2.3

  # Pull to refresh:
  pull_to_refresh: ^2.0.0

  # Action sheet for availability button(UI):
  adaptive_action_sheet: ^2.0.2

  # Direct call to the number:
  flutter_phone_direct_caller: ^2.1.1

  # Web View:
  webview_flutter: 2.8.0

  # Google Ads:
  google_mobile_ads: ^2.3.0

  # To initialize Firebase:
  firebase_core: ^2.8.0

  # To use Firebase Authentication(Google & Apple):
  firebase_auth:

  # Google sign in:
  google_sign_in:

  # Apple sign in:
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.2

  # Handle Notification via FCM:
  firebase_messaging: ^14.3.0

  # Copy text to clipboard
  clipboard: ^0.1.3

  # To handle permissions:
  permission_handler: ^10.2.0

  # To handle push notifications:
  flutter_local_notifications: ^8.2.0

  # Chat UI:
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6

  # To show graph:
  syncfusion_flutter_charts: ^21.1.35

  # To show country picker:
  country_picker: ^2.0.20

 # To show google map:
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2

  # To show calender:
  table_calendar: 3.0.8

  # To show device settings:
  app_settings: ^4.2.0

  # To show Rate App option:
  in_app_review: ^2.0.6

  # In App Purchase(RevenueCat):
  purchases_flutter: ^4.11.1

  # To send Message:
  flutter_sms: ^2.3.3

  # Share invite code:
  share_plus: ^6.3.1

  # To format date and time:
  intl: 0.17.0

  # To manage Geofencing:
  geofence_service: ^3.5.0

  # To pick image or capture image:
  image_picker: ^0.8.7+1

  # To manage connectivity:
  connectivity_plus: ^3.0.4

  # To open an adaptive dialog-box:
  adaptive_dialog: ^1.8.3

  # To request critical alert permission:
  flutter_critical_alert_permission_ios: ^0.1.0

  # To get device info:
  device_info_plus: ^8.2.0

  # Photo view:
  photo_view: ^0.14.0

  # To launch url:
  url_launcher: ^6.1.10

  awesome_notifications: ^0.7.4+1

  flutter_html: ^3.0.0-alpha.6
  awesome_notifications_fcm: ^0.7.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
#  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
